### ISSUE TITLE
500 error page breaks press

### ISSUE THREAD

**Issue by dabeeeenster** [dirkmc/press#4]
If you set up a 500 error response page (in app/views/errors), none of the press directives work.

**Comment by dirkmc** [comment]
Do you mean that when there is a 500 error, the press directives don't work?
I thought I had added something to the documentation about that but it seems I hadn't yet, I'll do so soon.

The problem is that when there's a 500 error, play invokes the 500.html template, but doesn't tell plugins when it's finished rendering, so there's no way for the press plugin to scan through the response and find javascript/css files that need to be compressed.

My suggestion is to not use compression in the error template. ie use #{script 'myscript.js'} instead of {press.script 'myscript.js}

**Comment by dabeeeenster** [comment]
OK thanks for the info.

**Comment by dabeeeenster** [comment]
Is this a "bug" in Play? Or does it have to abort the processing due to the error?

**Comment by dirkmc** [comment]
It's not really a bug..

Play tells plugins about a number of events, such as applicationStart, beforeInvocation, afterInvocation etc. Normally press watches out for afterActionInvocation, because that's when the response has been rendered and is ready to be delivered to the client. press scans the response for javascript that needs to be compressed. If there's an error, play tells the plugin with onInvocationException and aborts rendering of the called template.

However if you have a 500.html defined, it sees that it's a template, so it calls render template on that, but without informing the plugin of any of the events mentioned above. Now we're in the "error state" for this request, so it doesn't really make sense to do so. Perhaps they could add an afterErrorTemplateInvocation but it's a very specific use case, I don't believe they'd really think it's worth it.

Now I think about it, maybe it makes sense for press to watch out for onInvocationException so it knows that it's now in the error state, and then when the #{press.script} tag is invoked it can just output the uncompressed version of the file. Seems like a reasonable thing to do, certainly better than just dying ungracefully.

I'll implement that behaviour and fix the relative urls thing this week.

If you're curious, here's the plugin class that all plugins extend. It contains all the "events" (methods you can override):
http://github.com/playframework/play/blob/master/framework/src/play/PlayPlugin.java

**Comment by dirkmc** [comment]
I've now implemented the fix I suggested above - if there's an exception press will just output the original file instead of the compressed version.

**Comment by dirkmc** [comment]
Thanks for the bug report, they're very helpful!

**Comment by dabeeeenster** [comment]
Great thanks for the new build
